// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dreeuacqovhldjhlynio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZWV1YWNxb3ZobGRqaGx5bmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MTg5NzcsImV4cCI6MjA3Njk5NDk3N30.gW1xEBhwUpGvejEEaHhxWR0Pw74oU5uIUYgwtteIP94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});